article/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views

app_name='article'
urlpatterns = [
   #url(r'^$', views.articlelist, name='articlelist'),                                                 # 已修改为使用分页-不能再使用
   url(r'^$', views.ArticlelistView.as_view(), name='articlelist'),                                    #ok 与home index 一致  改为 基于类的 通用视图
   #url(r'(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),               # 已修改为使用分页-不能再使用
   url(r'(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.Archivesview.as_view(), name='archives'),  # 改为 基于类的 通用视图 archives 归档文章列表
   #url(r'^category/(?P<pk>\d+)/$', views.category, name='category'),                                  # 已修改为使用分页-不能再使用
   url(r'^category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name='category'),                     # 改为 基于类的 通用视图 catrgory 文章列表
   url(r'^tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tagurl'),                                 # 改为 基于类的 通用视图 tag      文章列表
   url(r'(?P<id>\d+)/$', views.detail, name='detail'),                                                 # 文章详情
   #url(r'(?P<id>\d+)/$', views.ArticleDetailView.as_view(), name='detail'),                           # xx error
]

comments/urls.py
# coding:utf-8
from django.conf.urls import url

from . import views

app_name='comments'
urlpatterns =[
    url(r'^comment/article/(?P<article_pk>[0-9]+)/$',views.article_comment,name='article_comment'),                       #一般文章的评论提交
    url(r'^comment/independentarticle/(?P<article_pk>[0-9]+)/$',views.independentarticle_comment,name='independentarticle_comment'), #独立文章的评论提交
]

gzystation/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articlelist/', include('article.urls',namespace='articlelist')),                          #文章列表
    url(r'^article/', include('article.urls',namespace='article')),                                  #一般文章
    url(r'^independentarticle/', include('independentarticle.urls',namespace='independentarticle')), #独立文章
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^search/', include('haystack.urls')),
    url(r'^user/',include('users.urls')),                                                            #用户注册激活
    url(r'', include('home.urls',namespace='home')),
    url(r'', include('comments.urls',namespace='comments')),
    

]

home/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
   #url(r'^$', views.index, name='index'),
   url(r'^$', views.IndexView.as_view(), name='index'), #基于类的 通用视图

]

comments/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=100,verbose_name="评论者")
    email = models.EmailField(max_length=255,verbose_name="Email地址")
    url = models.URLField(blank=True)
    text = models.TextField(verbose_name="评论")
    create_time = models.DateTimeField(auto_now_add=True,verbose_name="评论时间")

    article= models.ForeignKey('article.Article',blank=True,null=True,verbose_name="所属文章")
    #独立文章 与 一般文章 共用一套评论，所以增加一个外键
    independentarticle= models.ForeignKey('independentarticle.Independentarticle',blank=True,null=True,verbose_name="所属独立文章")

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '所有评论'

 
    def __str__(self):
        return self.text[:20]


    

home/models.py
from django.db import models

# Create your models here.

class Visitors(models.Model):
    #Visit_day = models.DateField(auto_now_add=True,editable=True,blank=True,verbose_name="日期")
    Visit_day = models.DateField(verbose_name="日期")
    #Visit_time = models.DateTimeField(auto_now_add=True,verbose_name="访问时间")
    Visitors_number = models.PositiveIntegerField(default=0, verbose_name="访问人数")
    
    class Meta:
        verbose_name = '访客统计'
        verbose_name_plural = '访客量统计'
        #默认排序
        ordering=['-Visit_day']

    def __str__(self):
        return str(self.Visit_day)

    #统计浏览量
    def increase_Visitors_number(self):
        self.Visitors_number += 1
        self.save(update_fields=['Visitors_number'])

independentarticle/models.py
# coding:utf-8
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse

import markdown
from django.utils.html import strip_tags
# Create your models here.

class Category(models.Model):
    #分类名称
    name = models.CharField(max_length=50,verbose_name="分类名称")

    class Meta:
        verbose_name = '独立文章分类名称'
        verbose_name_plural = '独立文章分类名称'

    def __str__(self):
        return self.name

    def get_article_num(self):
        num= Category.objects.filter(article__category__name=self.name).count()
        return num 


class Tag(models.Model): 
    #名称 
    name = models.CharField(max_length=50,verbose_name="标签名称")
    
    #admin界面中Tag项目显示的名称
    class Meta: 
        verbose_name = '独立文章标签名称'
        verbose_name_plural = '独立文章标签名称'
    
    #admin界面中每个项目显示自己的name
    def __str__(self):
        return self.name

class Independentarticle(models.Model):
    #文章标题
    title = models.CharField(max_length=70,verbose_name="文章标题")
    #文章内容
    body = models.TextField(verbose_name="文章内容",default='')
    #创建时间
    create_time = models.DateTimeField(verbose_name="创建时间")
    #修改时间
    modified_time = models.DateTimeField(verbose_name="修改时间")
    #摘要
    excerpt = models.CharField(max_length=200,blank=True,verbose_name="摘要")
    #分类
    category = models.ForeignKey(Category,verbose_name="分类")
    #标签
    tags = models.ManyToManyField(Tag,blank=True,verbose_name=u"标签")
    #作者
    author = models.ForeignKey(User,verbose_name="作者")
    #浏览量
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")


    class Meta:
        verbose_name = '独立文章'
        verbose_name_plural = '独立文章'
        #默认排序
        ordering=['-create_time']

    #自动生成摘要
    def save(self,*args,**kwargs):
        if not self.excerpt:
            
            md= markdown.Markdown(
                extensions=[
                           'markdown.extensions.extra',
                           'markdown.extensions.codehilite',
                           ]
                )
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Independentarticle,self).save(*args,**kwargs)


    def __str__(self):
        return self.title



    #定义 get_absolute_url 方法 获取自身的url 
    def get_absolute_url(self):
        # urls.py   中 request 传入的是 id
        # views.py  中 get_object_or_404()函数传入 pk 参数 id
        return reverse('independentarticle:detail',kwargs={'id':self.pk})
        # article --> independentarticle/urls.py app_name=independentarticle
        # detail  --> independentarticle/urls.py name='detail'

    #统计浏览量
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

users/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.


import os
import hashlib



class UserExt(models.Model):
    user = models.OneToOneField(User,verbose_name="用户名")                              #与User 表 建立一对一关系
    realname = models.CharField(max_length=64,verbose_name="真实姓名")                   # 真实姓名
    birthday = models.DateTimeField(blank=True,verbose_name="生日")                      # 生日
    nickname = models.CharField(max_length=64,blank=True,verbose_name="昵称")            # 昵称
    avatar = models.CharField(max_length=256,blank=True,verbose_name="头像")             # 头像
    telephone = models.CharField(max_length=32,blank=True,verbose_name="电话")           # 电话
    score = models.IntegerField(default=0,verbose_name="积分")                           # 积分
    logintime = models.DateTimeField(verbose_name="登陆时间")                            # 登录时间
    validkey = models.CharField(max_length=256,blank=True,verbose_name="验证key")        # key
    status = models.IntegerField(default=0,verbose_name="账号状态")                      # 状态

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'

    @classmethod
    def gen_validkey(cls):
        m = hashlib.md5()
        m.update(os.urandom(32))
        #生成一个随机数，并用MD5加密
        return m.hexdigest()

    def __str__(self):
        return self.realname
   
    def nickname_text(self):
        return self.user.username if self.nickname == '' else self.nickname

comments/forms.py
# coding:utf-8

from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','url','text']

comments/views.py
# coding:utf-8
from django.shortcuts import render,get_object_or_404,redirect
from article.models import Article
from independentarticle.models import Independentarticle

from .models import Comment
from .forms import CommentForm

# Create your views here.


#一般文章的评论提交
def article_comment(request,article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    print('article:',article)
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article     
            
            comment.save()

            return redirect(article)

        else:
            comment_list = article.comment_set.all()
            context ={
                     'article':article,
                     'form':form,
                     'comment_list':comment_list
                     }        
            return render(request,'article/article.html',context=context)
     
    return redirect(article)


#独立文章的评论提交
def independentarticle_comment(request,article_pk):
    article = get_object_or_404(Independentarticle,pk=article_pk)
    print('in-article:',article)
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.independentarticle = article  #comment.independentarticle 外键

            comment.save()

            return redirect(article)

        else:
            comment_list = article.comment_set.all()
            context ={
                     'article':article,
                     'form':form,
                     'comment_list':comment_list
                     }
            return render(request,'independentarticle/independentarticle.html',context=context)

    return redirect(article)

home/views.py
#coding:utf-8
from django.shortcuts import render

# Create your views here.
from article.models import Article,Tag,Category
from home.models import Visitors
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import time

def index(request):
    #return HttpResponse("时空构建中")
    #context ={'title':'川陀图书馆','text':'时空构建中' }
    #return render(request,'home/index.html',context)

    articles = Article.objects.all().order_by('-create_time')[:10]

    context = {'articles':articles}
    return render(request,'home/index.html',context)

#基于类 的通用视图
class IndexView(ListView):
    model= Article
    template_name = 'home/index.html'
    context_object_name = 'articles'
 
    #分页功能
    paginate_by = 7
    
    def get_context_data(self,**kwargs):
        context =super().get_context_data(**kwargs)
        
        #访客人数统计 +1
        day = str(time.strftime('%Y-%m-%d',time.localtime(time.time())))
        print(day)
        #access = get_object_or_404(Visitors,Visit_day=day)
        
        #access = Visitors.objects.filter(Visit_day=day)
        #if access :
        #    access[0].increase_Visitors_number()        
        #else:
        #    Visitors.objects.create(Visit_day=day,Visitors_number=1)

        #filter返回的是一个对象列表，所以model调用时需要指向为[0]
        #get返回的是对象,可以直接调用model函数，但是当get查询为空时会报错，所以需要使用try

        try:
            access = Visitors.objects.get(Visit_day=day)
            access.increase_Visitors_number()
        except Exception as e:
            print(e)
            access = Visitors.objects.create(Visit_day=day,Visitors_number=1)   

        paginator= context.get('paginator')
        page = context.get('page_obj')
        is_paginated= context.get('is_paginated')
        #print(paginator,page,is_paginated)
        pagination_data = self.pagination_data(paginator,page,is_paginated)
   
        #print(pagination_data)
        context.update(pagination_data)

        return context

    def pagination_data(self,paginator,page,is_paginated):
        if not is_paginated:
        
             return {}

        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
       
        page_number = page.number
        total_pages = paginator.num_pages

        page_range = paginator.page_range

        if page_number == 1 :
            right = page_range[page_number:page_number +2 ]
            if right[-1] < total_pages - 1:
                right_has_more = True

            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            left = page_range[(page_number -3 ) if (page_number -3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        else:
            left = page_range[(page_number - 3) if (page_number -3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages - 1:
               right_has_more = True
            if right[-1] < total_pages:
               last = True

            if left[0] > 2:
               left_has_more = True
            if left[0] > 1:
               first = True
    
        data = {
            'left':left,
            'right': right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
             }
        print(data)
        return data

home/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- 每个 include html文件中 都需要 标注 加载静态变量 “{% load staticfiles %}” -->
<html class="no-js">

{% include 'head.html' %}

<body>
{% include 'topline.html' %}


<div class="banner-bar">
    <div class="container">
        <div class="col-12 columns">
            <div class="place">
		{% block path %} {% endblock %}
            </div>
        </div>
    </div>
</div>

{% block content %}{% endblock %}





<!--MOB SHARE BEGIN-->

<!--
<div class="-mob-share-ui-button -mob-share-open">分享</div>
    <div class="-mob-share-ui" style="display: none">
        <ul class="-mob-share-list">
            <li class="-mob-share-weibo"><p>新浪微博</p></li>
            <li class="-mob-share-qzone"><p>QQ空间</p></li>
            <li class="-mob-share-qq"><p>QQ好友</p></li>
            <li class="-mob-share-weixin"><p>微信</p></li>
            <li class="-mob-share-douban"><p>豆瓣</p></li>
            <li class="-mob-share-facebook"><p>Facebook</p></li>
            <li class="-mob-share-twitter"><p>Twitter</p></li>
            <li class="-mob-share-pocket"><p>Pocket</p></li>
            <li class="-mob-share-google"><p>Google+</p></li>
            <li class="-mob-share-youdao"><p>有道云笔记</p></li>
            <li class="-mob-share-mingdao"><p>明道</p></li>
            <li class="-mob-share-tumblr"><p>Tumblr</p></li>
            <li class="-mob-share-instapaper"><p>Instapaper</p></li>
            <li class="-mob-share-linkedin"><p>LinkedIn</p></li>
        </ul>
        <div class="-mob-share-close">取消</div>
    </div>
<div class="-mob-share-ui-bg">
</div>
<script id="-mob-share" src="{% static 'home/js/mob-share.js' %}"></script>
-->
<!--MOB SHARE END-->

<div class="qqlist">
    <h3>订阅本站<small>(RSS)</small></h3>
    <form method="post" target="_blank" action="https://list.qq.com/cgi-bin/qf_compose_send">
    <input type="hidden" value="qf_booked_feedback" name="t" />
    <input type="hidden" value="dace5c2b356504de449e7f3fc2bb59f3f6124d6563786446" name="id" />
    <input type="text" placeholder="E-mail" value="" class="rsstxt" name="to" id="to" />
    <button type="submit" >订阅&rarr;</button>
    </form>
</div>

</div><!-- ?? -->


<div class="post-single type-post text-center">
    <h3 style="margin-top: 0">欢迎关注公众号~</h3>
        <img src="{% static 'home/picture/wx.jpg' %}" alt="">
</div>



{% block comment %}{% endblock %}

{% include 'noclear.html' %}


{% include 'bottomscrtpt.html' %}


</body>

</html>

home/templates/bottomscrtpt.html
{% load staticfiles %}
<a href="#" id="go-top">Top ↑</a>
<script src="{% static 'home/js/jquery.appear.js' %}"></script>
<script src="{% static 'home/js/config.js' %}"></script>
<script>^M
var _hmt = _hmt || [];^M
(function() {^M
  var hm = document.createElement("script");^M
  hm.src = "https://hm.baidu.com/hm.js?ad9ab5e37c2811b9f0979e46123fc898";^M
  var s = document.getElementsByTagName("script")[0]; ^M
  s.parentNode.insertBefore(hm, s);^M
})();^M
</script>

<script src="{% static 'home/js/jquery.fancybox.pack.js' %}"></script>
<script>
$(document).ready(function () {
    $(".entry a").each(function (i, e) {
        if(e.host != 'www.leavesongs.com') {
            e.target = '_blank';
        }
    });
    $(".entry img").each(function (i, e) {
        if(e.parentNode.tagName.toUpperCase() != 'A') {
            $(e).wrap('<a href="'+escapeHtml(e.src)+'" class="fancybox"></a>');
        } else {
            $(e.parentNode).addClass('fancybox');
        }
    });
    $('.fancybox').fancybox();
})
</script>

home/templates/comment.html
{% load staticfiles %}
{% load blog_tags %}


<div id="comments" class="comments">
    <h3>已有{{ article.comment_set.count }}条评论</h3>
    <ol class="comment-list">
        {% for comment in comment_list %}
        <li class="comment-body">
            <div class="clearfix">
               <div class="comment-author">
                   <img src="{% static 'comments/picture/comment_name.png' %}">
               </div>
               <div class="comment-meta">
                    <div class="fn">
                       <a href="">{{ comment.name }}</a>
                    </div>
                    <p>{{ comment.text }}</p>
                    <span class="comment-time">时间:{{ comment.create_time }}</span>
               </div>
            </div>
        </li>
        {% empty %}
        暂无评论
        {% endfor %}

    </ol>
</div>


<div id="reply">
</div>

<div id="comment-place">
    <div id="comment-post" class="respond none-resize">
        <div id="respond">
            <h3 id="response">添加新评论</h3>
            <form method="post" id="comment-form" role="form" action="{% url 'comments:article_comment' article.pk %}">
                {% csrf_token %}
                <p>
                    <label for="{{ form.name.id_for_label }}" class="required">称呼</label>
                    <!-- <input type="text" name="nickname" value="" placeholder="昵称" maxlength="64" required id="id_nickname" /> -->
                    {{ form.name }}
                    {{ form.name.errors }}
                </p>
                <p>
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    <!-- <input type="text" name="email" value="" placeholder="邮箱（可留空）" maxlength="254" id="id_email" /> -->
                    {{ form.email }}
                    {{ form.email.errors }}
                </p>
                <p>
                    <label for="{{ form.url.id_for_label }}">网站</label>
                    <!-- <input type="text" name="url" value="" placeholder="链接（可留空）" maxlength="200" id="id_url" /> -->
                    {{ form.url }}
                    {{ form.url.errors }}
                </p>
                <p>
                    <label for="{{ form.text.id_for_label }}" class="required">内容</label>
                    <!-- <textarea name="content" cols="40" rows="6" required id="id_content"></textarea> -->
                    {{ form.text }}
                    {{ form.text.errors}}
                </p>
                <!--                
                <p>
                    <label style="float:left;">验证码</label>
                    <div class="row" style="margin-top: 8px">
                    <div class="col-xs-4"><input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" placeholder="验证码" /> <input id="id_captcha_0" name="captcha_0" type="hidden" value="bf1a523df57b7cccdbcb030128087c17914b2270" />
    	            </div>
                    <div class="col-xs-4">
    	                <img src="picture/e79da8a0db0947aebdcca042b1f8b118.gif" alt="captcha" class="captcha" height="25" />
                    </div>  
                    </div> 
                </p>
                -->
                <p>
                    <button type="submit" class="submit">提交评论</button>
                </p>
            </form>
        </div>
    </div>
</div>

home/templates/noclear.html
{% load staticfiles %}
{% load blog_tags %}


<!--评论 comment.html-->
</div>

<!-- col-11 end-->


<div  class="col-5 columns" id="sidebar" role="complementary">


  <div class="widget widget_search">
    <h3>搜索</h3>
    <form action="{% url 'haystack_search' %}" id="searchform" method="get">
        <input type="search" id="searchkey" name="q" value="" class="searchkey" placeholder="Search..."/>
        <button type="submit"  id="searchsubmit">Go</button>
    </form>
  </div>

<!--
  <div class="widget">
        <h3 class="widget-title">最新评论</h3>
        <ul class="widget-list" id="recent-comment">


        <li id="comment" class="clearfix">
            <img class="avatar" src="picture/591e70d58dd0efbe1da3cb83f2f3c0c0.jpg" alt="%s" width="40" height="40">
            <div class="comments-link"><cite>影乐</cite>：<a href="/other/tinger.html#comment-2914">学长厉害了</a></div>
        </li>

        <li id="comment" class="clearfix">
            <img class="avatar" src="picture/d41d8cd98f00b204e9800998ecf8427e.jpg" alt="%s" width="40" height="40">
            <div class="comments-link"><cite>&lt;audio src=x onerror=alert(&#39;audio&#39;);&gt;</cite>：<a href="/PENETRATION/getshell-via-ssrf-and-redis.html#comment-2913">&lt;audio src=x onerror=alert(&#39;audio&#39;);&gt;^M煮屎者</a></div>
        </li>

        <li id="comment" class="clearfix">
            <img class="avatar" src="picture/2f2224c85fe48ba7ab31fb3100745d53.jpg" alt="%s" width="40" height="40">
            <div class="comments-link"><cite>墨攻</cite>：<a href="/PENETRATION/metinfo-5.3.17-sql-injection.html#comment-2912">最近在审计一个小的cms，看了半天竟然没发现漏洞，我开始怀职业了，不知大佬能否帮忙看一下...</a></div>
        </li>

        <li id="comment" class="clearfix">
            <img class="avatar" src="picture/d41d8cd98f00b204e9800998ecf8427e.jpg" alt="%s" width="40" height="40">
            <div class="comments-link"><cite>Kyrie</cite>：<a href="/PENETRATION/django-debug-page-xss.html#comment-2910">这里会不会造成类似jinjia2模板注入的问题，如果有的话是不是就从一个XS变成一个RCE了</a></div>
        </li>

        <li id="comment" class="clearfix">
            <img class="avatar" src="picture/c4267eb6d17276fa31c547ac71611e90.jpg" alt="%s" width="40" height="40">
            <div class="comments-link"><cite>phithon</cite>：<a href="/PENETRATION/django-debug-page-xss.html#comment-2911">@Kyrie 不会，因为不存在模板字符串拼接，而且Django的模板沙箱厉害。</a></div>
        </li>

    </ul>
  </div>

-->

<!--分类-->
        <div class="widget widget-category">
            <h3>分类</h3>
            {% get_categories as category_list %}
            <ul id="blogsort" class="widget-list">
                {% for category in  category_list %}
                <li>
                    <a href="{% url 'article:category' category.pk %}" >{{ category.name }}<em style="box-sizing:content-box;">{{ category.get_article_num}}</em></a>
                </li>
                {% empty %}
                暂无分类
                {% endfor %}
            </ul>
        </div>

<!--
  <div class="widget widget-recent-entries">
        <h3 class="widget-title">热门日志</h3>
        <ul id="hotlog" class="widget-list">


        <li><a href="/PHP/phpdelfile.html">php遍历目录&amp;删除指定文件中指定内容</a></li>

        <li><a href="/THINK/banjia.html">博客搬家成功</a></li>

        <li><a href="/PENETRATION/vps-pentest.html">对自己VPS的一次安全检测</a></li>

        <li><a href="/C/CGIforC_1.html">C语言CGI编程入门(一)</a></li>

        <li><a href="/C/gh0st_2.html">gh0st源码分析与远控的编写(二)</a></li>

    </ul>
  </div>

-->


        <div class="widget widget-recent-entries">
            <h3 class="widget-title">最新文章</h3>
            {% get_recent_articles as recent_article_list %}
            <ul id="hotlog" class="widget-list">
                {% for article in recent_article_list %}
                <li>
                    <a href="{{ article.get_absolute_url}}">{{ article.title }}</a>
                </li>
                {% empty %}
                暂无文章
                {% endfor %}
            </ul>
        </div>

</div>
</div>

<div id="footer">
        <!-- copyright -->
        <div class="container">
                <div class="row remove-bottom">
                        <div class="col-6 columns">
                        <h3>Little About</h3>
                        <p>
                           Ender451 科幻、技术爱好者  <br>
                           现居 北京 <br>
                           爱好：读书 游戏 <br>
                           欢迎各位来串门 <br>
                           E-mail：Ender451@qq.com
                        </p>
                        </div>

                        <div class="col-10 columns">

                                <h3 class="mobile-hide">Follow me</h3>
        <div id="social-links">
          <a href="http://weibo.com/" class="sweibo" target="_blank" title="新浪微博">新浪微博</a>
          <a href="javascript:alert(/没有腾讯微博哟/)" class="qweibo" target="_blank" title="腾讯微博">腾讯微博</a>
          <a href="javascript:alert(/墙外有什么/);window.open('http://google.com')" class="google" target="_blank" title="墙外的世界">google+</a>
          <a href="https://github.com/Ender451" class="github" target="_blank" title="Github">github</a>
          <a href="javascript:confirm(/mailto:Ender451@qq.com/)" class="mail" target="_blank" title="私信给我">私信给我</a>
          <a href="/feed/" target="_blank" class="rss" title=:"川陀图书馆">RSS订阅</a>
        </div>
        <div class="bot-line"></div>
                                <p class="copyright">
        Copyright &copy; Powered by talkbook
                                &nbsp;&nbsp;<i>Designed and built with all the love in the world by <a href="https://www.leavesongs.com" target="_blank">Phithon</a> && deepsky </i>
<!--
                    <a href="/template/change/">更换模板</a>
-->
                                </p>
                        </div>
                </div>
        </div>
        <!-- /copyright -->
</div>

home/templates/topline.html
{% load staticfiles %}
<!--[if lt IE 8]>
    <div class="browsehappy" role="dialog">当前网页 <strong>不支持</strong> 你正在使用的浏览器. 为了正常的访问, 请 <a href="http://browsehappy.com/">升级你的浏览器</a>.</div>
<![endif]-->
<div id="header">
    <div class="container">
        <h1 class="h1-title">
            <a href="{% url 'home:index' %}" style="text-decoration:none">
               <img src="{% static 'home/picture/pythonlogo.png' %}" alt="川陀图书馆" />
               The Trantor Library
            </a>
        </h1>
        <div id="nav">
        <input type="checkbox" id="button">
        <label for="button" onclick>菜单</label>
        <ul>
            <li class="item ">
                <a href="{% url 'home:index' %}" >首页</a>
            </li>
            <li class="item ">
                <a href="/articlelist/" >文章</a>
            </li>
            
            <li class="item ">
                <a href="/independentarticle/1" >关于</a>
            </li>
            
            <li class="item ">
                <a href="/independentarticle/2" >友链</a>
            </li>
            
            <li class="item ">
                <a href="https://github.com/Ender451" target="_blank" >项目</a>
            </li>

            <li class="item ">
                <a href="http://blog.guozhongyuan.cn/admin" >管理</a>
            </li>
            
            <li class="item ">
                <a href="https://www.guozhongyuan.cn" >Jumpserver</a>
            </li>

            <li class="item ">
                <a href="http://blog.guozhongyuan.cn/user/" >用户</a>
            </li>
            
        </ul>
        
        </div>
    </div>
</div>