gzystation/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articlelist/', include('article.urls',namespace='articlelist')),                          #文章列表
    url(r'^article/', include('article.urls',namespace='article')),                                  #一般文章
    url(r'^independentarticle/', include('independentarticle.urls',namespace='independentarticle')), #独立文章
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^search/', include('haystack.urls')),
    url(r'^user/',include('users.urls')),                                                            #用户注册激活
    url(r'', include('home.urls',namespace='home')),
    url(r'', include('comments.urls',namespace='comments')),
    

]

home/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
   #url(r'^$', views.index, name='index'),
   url(r'^$', views.IndexView.as_view(), name='index'), #基于类的 通用视图

]

users/urls.py
#encoding: utf-8

from django.conf.urls import url

from .views import RegisterView,ActiveView,\
                   LoginView,LogoutView,\
                   ResetPasswordView,ResetPasswordConfirmView, \
                   ModifyPasswordView,ChangePasswordView,\
                   UserExtBaseView,UserExtAvatarView
                                             #导入 views.py 中的 类
 
from . import views                          #引入 views.py 中的 函数

app_name = 'users'
urlpatterns = [
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.test, name='test'),                         #测试页面
    url(r'^register/', RegisterView.as_view(), name='register'), #基于类的 注册用户  
    url(r'^active/', ActiveView.as_view(),name='active'),        #         激活用户
    url(r'^login/', LoginView.as_view(), name="login"),
    url(r'^logout/', LogoutView.as_view(), name="logout"),
    url(r'^modify_password/', ModifyPasswordView.as_view(), name="modify_password"),
    url(r'^reset_password/', ResetPasswordView.as_view(), name="reset_password"),
    url(r'^reset_password_confirm/', ResetPasswordConfirmView.as_view(), name="reset_password_confirm"),
    url(r'^change_password/', ChangePasswordView.as_view(), name="change_password"),
    url(r'^user_ext_base/', UserExtBaseView.as_view(), name="user_ext_base"),
    url(r'^user_ext_avatar/', UserExtAvatarView.as_view(), name="user_ext_avatar"),
]

users/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.


import os
import hashlib



class UserExt(models.Model):
    user = models.OneToOneField(User,verbose_name="用户名")                              #与User 表 建立一对一关系
    realname = models.CharField(max_length=64,verbose_name="真实姓名")                   # 真实姓名
    birthday = models.DateTimeField(blank=True,verbose_name="生日")                      # 生日
    nickname = models.CharField(max_length=64,blank=True,verbose_name="昵称")            # 昵称
    avatar = models.CharField(max_length=256,blank=True,verbose_name="头像")             # 头像
    telephone = models.CharField(max_length=32,blank=True,verbose_name="电话")           # 电话
    score = models.IntegerField(default=0,verbose_name="积分")                           # 积分
    logintime = models.DateTimeField(verbose_name="登陆时间")                            # 登录时间
    validkey = models.CharField(max_length=256,blank=True,verbose_name="验证key")        # key
    status = models.IntegerField(default=0,verbose_name="账号状态")                      # 状态

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'

    @classmethod
    def gen_validkey(cls):
        m = hashlib.md5()
        m.update(os.urandom(32))
        #生成一个随机数，并用MD5加密
        return m.hexdigest()

    def __str__(self):
        return self.realname
   
    def nickname_text(self):
        return self.user.username if self.nickname == '' else self.nickname

users/views.py
# Create your views here.
import datetime
import json
import os
import time


from django.views.generic import View,FormView
from django.views.generic.base import TemplateResponseMixin

from .models import UserExt
from .forms import RegisterForm,LoginForm,ResetPasswordForm,ResetPasswordConfirmForm,ChangePasswordForm,UserExtBaseForm,UserExtAvatarForm
from .mixins import LoginRequiredMixin

from django.utils import timezone
from django.utils.decorators import method_decorator
from django.http import JsonResponse,HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages

from django.db import transaction #事务

from django.conf import settings
from home.models import Visitors


class RegisterView(View):


    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        print('-------------------------------------')
        return self._register(form)


    def _register(self, form):
        if form.is_valid():
            username = form.cleaned_data.get('username', '')
            password = form.cleaned_data.get('password', '')
            email = form.cleaned_data.get('email', '')
            print('======')
            print('username:',username,'password:',password,'email:',email)   
            try:
                with transaction.atomic():
                    user = User.objects.create_user(username=username, password=password, email=email)
                    validkey = UserExt.gen_validkey()
                    user_ext = UserExt.objects.create(user=user, realname='', birthday=datetime.date(1945, 1, 1), \
                                                        nickname=username, avatar='default', telephone='', logintime=timezone.now(), validkey=validkey)
                    content = '欢迎注册[川陀图书馆], 请点击此处进行激活用户: http://blog.guozhongyuan.cn/user/active/?username={username}&validkey={validkey}'.format(username=username, validkey=validkey)
                    send_mail('[川陀图书馆]用户注册', content, settings.EMAIL_HOST_USER, [email])
            except BaseException as e:
                return JsonResponse({'status': 500, 'errors' : ['服务器错误']})
            return JsonResponse({'status': 200})
        else:
            return JsonResponse({'status': 400, 'errors': json.loads(form.errors.as_json()), 'result': ''})




    def get(self,request,*args,**kwargs):
        username = request.GET.get('username','')
        password = request.GET.get('password','')
        email = request.GET.get('email','')
      
        nickname = request.GET.get('nickname','')
        realname = nickname
        print("nickname:",nickname)

        user = User.objects.create_user(username=username,password=password,email=email)  #创建User
        validkey = UserExt.gen_validkey()                                                 #生成一个通过MD5加密的随机字符串作为验证秘钥
                                                                                          #创建与User一一对应的UserExt
        user_ext = UserExt.objects.create(user=user,realname=realname,birthday=datetime.date(1945,1,1),\
                                         nickname=nickname,avatar='default',telephone='',logintime=timezone.now(),validkey=validkey)

        content = '<a href="http://blog.guozhongyuan.cn/user/active/?username={username}&validkey={validkey}"> 点击此处进行激活  </a>'
        send_mail('User Register',content.format(username=username,validkey=validkey),settings.EMAIL_HOST_USER,[email])     #发送验证邮件


        return JsonResponse({'status': 200})




class ActiveView(View):

    def get(self,request,*args,**kwargs):

        username = request.GET.get('username','')
        validkey = request.GET.get('validkey','')
      
        print(username,validkey)
        user = User.objects.get(username=username)

        try:
            if user.userext.status == 0 and user.userext.validkey != '':
                if user.userext.validkey == validkey:   #当验证秘钥吻合，激活用户状态，清空秘钥，激活成功
                   user.userext.status = 1
                   user.userext.validkey = ''
                   user.userext.save()
                   return HttpResponse("激活成功")     
                else:                                   #当验证秘钥失败，返回验证码错误
                   return HttpResponse("验证码不正确")

            return HttpResponse("用户已经激活")         #如果用户状态已经处于激活状态，返回用户已激活

        except ObjectDoesNotExist as e:                 #无法得到正确对应验证信息，返回用户不存在

            pass

        #跳转到页面显示：
        return HttpResponse("用户不存在")



class LoginView2(View):
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            login(request, form.cached_user)
            return JsonResponse({'status' : 200, 'errors' : {}, 'result' : {}})
        else:
            return JsonResponse({'status' : 400, 'errors' : json.loads(form.errors.as_json()), 'result' : {}})



class LoginView(FormView):
    form_class = LoginForm

    def form_valid(self, form):
        login(self.request, form.cached_user)
        print('login ok')
        return JsonResponse({'status' : 200, 'errors' : {}, 'result' : {}})

    def form_invalid(self, form):
        print('login error')
        return JsonResponse({'status' : 400, 'errors' : json.loads(form.errors.as_json()), 'result' : {}})


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


class ModifyPasswordView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponse('success')
        else:
            return HttpResponse('fail')



class ResetPasswordView(FormView):
    template_name = 'user/reset_password.html'
    form_class = ResetPasswordForm

    def form_valid(self, form):
        try:
            with transaction.atomic():
                user = form.cached_user
                validkey = user.userext.gen_validkey()
                user.userext.validkey = validkey
                user.userext.save()
                content = '欢迎来到[川陀图书馆], 请点击此处进行重置用户: http://blog.guozhongyuan.cn/user/reset_password_confirm/?username={username}&validkey={validkey}'.format(username=user.username, validkey=validkey)
                send_mail('[川陀图书馆]用户重置密码', content, settings.EMAIL_HOST_USER, [user.email])
                messages.add_message(self.request, messages.INFO , '重置密码邮件已发送, 请查收邮件进行密码重置')
        except BaseException as e:
            print(e)
            messages.add_message(self.request, messages.ERROR, '重置密码邮件发送失败，请重试')

        return HttpResponseRedirect(reverse('index'))

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form' : form})




class ResetPasswordConfirmView(FormView):
    template_name = 'user/reset_password_confirm.html'
    form_class = ResetPasswordConfirmForm

    def get_initial(self):
        return self.request.GET

    def form_valid(self, form):
        user = form.cached_user
        password = form.cleaned_data.get('password', '')
        user.set_password(password)
        user.save()
        user.userext.validkey = ''
        user.userext.save()
        messages.add_message(self.request, messages.INFO, '重置密码成功，请重新登陆')
        return HttpResponseRedirect(reverse('index'))

    def form_invalid(self, form):
        return render(self.request, self.template_name, {'form' : form})


class ChangePasswordView(LoginRequiredMixin, FormView):
    form_class = ChangePasswordForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        password = form.cleaned_data.get('password', '')
        user.set_password(password)
        user.save()
        return JsonResponse({'status' : 200, 'errors' : {}, 'result' : None})

    def form_invalid(self, form):
        return JsonResponse({'status' : 400, 'errors' : json.loads(form.errors.as_json()), 'result' : None})




class UserExtBaseView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'user/user_ext.html'
    form_class = UserExtBaseForm
    form_class_avatar = UserExtAvatarForm

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
                                    'form' : self.form_class(instance=request.user.userext),
                                    'form_avatar' : self.form_class_avatar(instance=request.user.userext),
                                    'nav' : 'avatar'
                                    })

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=request.user.userext)
        if form.is_valid():
            model = form.save(commit=False)
            model.save()

        return self.render_to_response({
                                        'form' : form,
                                        'form_avatar' : self.form_class_avatar(instance=request.user.userext),
                                        'nav' : 'base'
                                        })



class UserExtAvatarView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'user/user_ext.html'
    form_class = UserExtBaseForm
    form_class_avatar = UserExtAvatarForm

    def get(self, request, *args, **kwargs):
        return self.render_to_response({
                                    'form' : self.form_class(instance=request.user.userext),
                                    'form_avatar' : self.form_class_avatar(instance=request.user.userext),
                                    'nav' : 'avatar'
                                    })

    def post(self, request, *args, **kwargs):

users/templates/user/reset_password.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- 每个 include html文件中 都需要 标注 加载静态变量 “{% load staticfiles %}” -->
<html class="no-js">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="川陀图书馆管理员的学习测试网站。" />
    <title>川陀图书馆 | 川陀图书馆</title>
    <link rel="alternate" type="application/atom+xml" href="/feed/" title="川陀图书馆" />

    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- sweetalert -->
    <link rel="stylesheet" type="text/css" href="{% static '/home/css/sweetalert.css' %}"/>
<!--
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js "></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js "></script>
-->
     
    <link href="{% static 'home/css/base.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'article/css/highlights/colorful.css' %}" rel="stylesheet" type="text/css" />

<!--
    <script src="{% static 'home/js/jquery-1.9.1.min.js' %}"></script>
    <script src="{% static 'home/js/common_tpl.js' %}" type="text/javascript"></script>
-->

    <!--add -->
    <script type="text/javascript" src="{% static '/home/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static '/home/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static '/home/js/sweetalert.min.js' %}"></script>


    <link rel="shortcut icon" href="/static/deep/images/favicon.ico" />

    
    <style>
       div.row .col-xs-4 {
         float: left;
         margin-left: 4px;
       }
       div.row .col-xs-4 img {
         margin-left: 5px;
       }
       span.highlighted {
           color:red;
       }
    </style>

    <link href="{% static 'home/css/jquery.fancybox.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/css/code.css' %}">
    

</head>


<body>


<div id="header">
    <div class="container">
        <h1 class="h1-title">
            <a href="{% url 'home:index' %}" style="text-decoration:none">
               <img src="{% static 'home/picture/pythonlogo.png' %}" alt="川陀图书馆" />
               The Trantor Library
            </a>
        </h1>
        <div id="nav">
        <input type="checkbox" id="button">
        <label for="button" onclick>菜单</label>
        <ul>
            <li class="item ">
                <a href="{% url 'home:index' %}" >首页</a>
            </li>
            <li class="item ">
                <a href="/articlelist/" >文章</a>
            </li>

            <li class="item ">
                <a href="/independentarticle/1" >关于</a>
            </li>

            <li class="item ">
                <a href="/independentarticle/2" >友链</a>
            </li>

            <li class="item ">
                <a href="https://github.com/Ender451" target="_blank" >项目</a>
            </li>

            <li class="item ">
                <a href="http://blog.guozhongyuan.cn/admin" >管理</a>
            </li>

            <li class="item ">
                <a href="http://www.guozhongyuan.cn" >Jumpserver</a>
            </li>

            <li class="item ">
                <a href="http://blog.guozhongyuan.cn/user/" >用户</a>
            </li>

        </ul>

        </div>
    </div>
</div>




<div class="banner-bar">
    <div class="container">
        <div class="col-12 columns">
            <div class="place">
            <div id="nav">
                    <a data-toggle="modal" data-target="#dialog_login" data-backdrop="static" style="cursor:pointer" >登录</a>
                
                    <a data-toggle="modal" data-target="#dialog_register" data-backdrop="static" style="cursor:pointer" >注册</a>
            </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
        <div class="col-11 columns" id="mainbody">
 
        <p>
        	<li>1</li>
        	<li>2</li>
        	<li>3</li>
        	<li>4</li>
        	<li>5</li>
        	<li>6</li>
        	<li>7</li>
        	<li>8</li>
        	<li>9</li>
        	<li>10</li>
        	<li>11</li>
        	<li>12</li>
        	<li>13</li>
        	<li>14</li>
        	<li>15</li>
        	<li>16</li>
        	<li>17</li>
        	<li>18</li>
        	<li>19</li>
        	<li>20</li>
        	<li>21</li>
        	<li>22</li>
        	<li>23</li>
        	<li>24</li>
        	<li>25</li>
        	<li>26</li>
        	<li>27</li>
        	<li>28</li>
        	<li>29</li>
        	<li>30</li>
        	<li>31</li>
        	<li>32</li>
        	<li>33</li>
        	<li>34</li>
        	<li>35</li>
        	<li>36</li>
        	<li>37</li>
        	<li>38</li>
        	<li>39</li>
        	<li>40</li>
        	<li>41</li>
        	<li>42</li>
        	<li>43</li>
        	<li>44</li>
        	<li>45</li>
        </p>

        </div>

        <div  class="col-5 columns" id="sidebar" role="complementary">

        </div>

</div>




        <!-- 登录 模态框 -->
	<div class="modal" id="dialog_login">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4>用户登录</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" role="form" method="post" id="form_login">
						{% csrf_token %}
						<div class="form-group">
							<label for="username" class="col-xs-4 control-label">用户名/邮箱</label>
							<div class="col-xs-6">
								<input type="text" class="form-control" name="username" id="username" placeholder="用户名/邮箱" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password" id="password" placeholder="密码" value="">
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-offset-4 col-xs-10">
								<button type="button" class="btn btn-primary" id="btn_login">登录</button>
								<button type="button" class="btn btn-link" id="btn_reset_password">忘记密码</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>



	<div class="modal" id="dialog_register">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4>用户注册</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" role="form" method="post" id="form_register">
						{% csrf_token %}
						<div class="form-group">
							<label for="username" class="col-xs-4 control-label">用户名</label>
							<div class="col-xs-6">
								<input type="text" class="form-control" name="username" id="username" placeholder="用户名" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="email" class="col-xs-4 control-label">邮箱</label>
							<div class="col-xs-6">
								<input type="text" class="form-control" name="email" id="email" placeholder="邮箱" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password" id="password" placeholder="密码" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password2" class="col-xs-4 control-label">确认密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password2" id="password2" placeholder="确认密码" value="">
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-offset-4 col-xs-10">
								<button type="button" class="btn btn-primary" id="btn_register">注册</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>


	<div class="modal" id="dialog_password">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4>修改密码</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" role="form" method="post" id="form_password">
						{% csrf_token %}
						<div class="form-group">
							<label for="old_password" class="col-xs-4 control-label">原密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="old_password" id="old_password" placeholder="原密码" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">新密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password" id="password" placeholder="密码" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password2" class="col-xs-4 control-label">确认密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password2" id="password2" placeholder="确认密码" value="">
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-offset-4 col-xs-10">
								<button type="button" class="btn btn-primary" id="btn_password">确定</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>


	<script type="text/javascript">
		jQuery(document).ready(function() {
			jQuery('#btn_register').on('click', function() {
				var params = jQuery('#form_register').serializeArray();
				jQuery.post("{% url 'users:register' %}", params, function(data) {
					if(data['status'] == 200) {
                                                console.log(" status = 200");
						jQuery('#dialog_register').modal('hide');
						swal({
							title: "注册成功",
							text: "请查收邮箱进行用户激活",
							type: "success",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 400) {
						var errors = [];
						jQuery.each(data['errors'], function(key, value) {
							errors.push(value[0]['message']);
						});
						swal({
							title: "验证失败",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 401) {
						var errors = data['errors'] || [];
						swal({
							title: "用户未登录",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if (data['status'] == 500) {
						var errors = data['errors'] || [];
						swal({
							title: "服务器错误",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else {

					}
				}, 'json')
			});

			jQuery('#btn_login').on('click', function() {
				var params = jQuery('#form_login').serializeArray();
				jQuery.post("{% url 'users:login' %}", params, function(data) {
					if(data['status'] == 200) {
                                                console.log(" status = 200");
						jQuery('#dialog_login').modal('hide');
						window.location.replace('/user/');
						// swal({
						// 	title: "登录成功",
						// 	text: "",
						// 	type: "success",
						// 	confirmButtonText: "确定"
						// });
					} else if(data['status'] == 400) {
						var errors = [];
						jQuery.each(data['errors'], function(key, value) {
							errors.push(value[0]['message']);
						});
						swal({
							title: "验证失败",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 401) {
						var errors = data['errors'] || [];
						swal({
							title: "用户未登录",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if (data['status'] == 500) {
						var errors = data['errors'] || [];
						swal({
							title: "服务器错误",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else {

					}
				}, 'json');
			});

			jQuery('#btn_reset_password').on('click', function() {
				window.location.replace("{% url 'users:reset_password' %}");
			});

			jQuery('#btn_password').on('click', function() {
				var params = jQuery('#form_password').serializeArray();
				jQuery.post("{% url 'users:change_password' %}", params, function(data) {
					if(data['status'] == 200) {
						jQuery('#dialog_password').modal('hide');
						swal({
							title: "修改密码成功, 请重新登陆",
							text: "",
							type: "success",
							confirmButtonText: "确定",
							closeOnConfirm: false,
						}, function() {
							swal.close();
							window.location.replace(window.location.href)
						});
					} else if(data['status'] == 400) {
						var errors = [];
						jQuery.each(data['errors'], function(key, value) {
							errors.push(value[0]['message']);
						});
						swal({
							title: "验证失败",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 401) {
						var errors = data['errors'] || [];
						swal({
							title: "用户未登录",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if (data['status'] == 500) {
						var errors = data['errors'] || [];
						swal({
							title: "服务器错误",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else {

					}
				}, 'json')
			});

		});
	</script>



</body>

</html>