article/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views

app_name='article'
urlpatterns = [
   #url(r'^$', views.articlelist, name='articlelist'),                                                 # 已修改为使用分页-不能再使用
   url(r'^$', views.ArticlelistView.as_view(), name='articlelist'),                                    #ok 与home index 一致  改为 基于类的 通用视图
   #url(r'(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),               # 已修改为使用分页-不能再使用
   url(r'(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.Archivesview.as_view(), name='archives'),  # 改为 基于类的 通用视图 archives 归档文章列表
   #url(r'^category/(?P<pk>\d+)/$', views.category, name='category'),                                  # 已修改为使用分页-不能再使用
   url(r'^category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name='category'),                     # 改为 基于类的 通用视图 catrgory 文章列表
   url(r'^tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tagurl'),                                 # 改为 基于类的 通用视图 tag      文章列表
   url(r'(?P<id>\d+)/$', views.detail, name='detail'),                                                 # 文章详情
   #url(r'(?P<id>\d+)/$', views.ArticleDetailView.as_view(), name='detail'),                           # xx error
]

comments/urls.py
# coding:utf-8
from django.conf.urls import url

from . import views

app_name='comments'
urlpatterns =[
    url(r'^comment/article/(?P<article_pk>[0-9]+)/$',views.article_comment,name='article_comment'),                       #一般文章的评论提交
    url(r'^comment/independentarticle/(?P<article_pk>[0-9]+)/$',views.independentarticle_comment,name='independentarticle_comment'), #独立文章的评论提交
]

gzystation/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articlelist/', include('article.urls',namespace='articlelist')),                          #文章列表
    url(r'^article/', include('article.urls',namespace='article')),                                  #一般文章
    url(r'^independentarticle/', include('independentarticle.urls',namespace='independentarticle')), #独立文章
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^search/', include('haystack.urls')),
    url(r'^user/',include('users.urls')),                                                            #用户注册激活
    url(r'', include('home.urls',namespace='home')),
    url(r'', include('comments.urls',namespace='comments')),
    

]

home/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
   #url(r'^$', views.index, name='index'),
   url(r'^$', views.IndexView.as_view(), name='index'), #基于类的 通用视图

]

independentarticle/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views

app_name='independentarticle'
urlpatterns = [
   url(r'(?P<id>\d+)/$', views.detail, name='detail'),      # 文章详情
]

independentarticle/models.py
# coding:utf-8
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse

import markdown
from django.utils.html import strip_tags
# Create your models here.

class Category(models.Model):
    #分类名称
    name = models.CharField(max_length=50,verbose_name="分类名称")

    class Meta:
        verbose_name = '独立文章分类名称'
        verbose_name_plural = '独立文章分类名称'

    def __str__(self):
        return self.name

    def get_article_num(self):
        num= Category.objects.filter(article__category__name=self.name).count()
        return num 


class Tag(models.Model): 
    #名称 
    name = models.CharField(max_length=50,verbose_name="标签名称")
    
    #admin界面中Tag项目显示的名称
    class Meta: 
        verbose_name = '独立文章标签名称'
        verbose_name_plural = '独立文章标签名称'
    
    #admin界面中每个项目显示自己的name
    def __str__(self):
        return self.name

class Independentarticle(models.Model):
    #文章标题
    title = models.CharField(max_length=70,verbose_name="文章标题")
    #文章内容
    body = models.TextField(verbose_name="文章内容",default='')
    #创建时间
    create_time = models.DateTimeField(verbose_name="创建时间")
    #修改时间
    modified_time = models.DateTimeField(verbose_name="修改时间")
    #摘要
    excerpt = models.CharField(max_length=200,blank=True,verbose_name="摘要")
    #分类
    category = models.ForeignKey(Category,verbose_name="分类")
    #标签
    tags = models.ManyToManyField(Tag,blank=True,verbose_name=u"标签")
    #作者
    author = models.ForeignKey(User,verbose_name="作者")
    #浏览量
    views = models.PositiveIntegerField(default=0, verbose_name="浏览量")


    class Meta:
        verbose_name = '独立文章'
        verbose_name_plural = '独立文章'
        #默认排序
        ordering=['-create_time']

    #自动生成摘要
    def save(self,*args,**kwargs):
        if not self.excerpt:
            
            md= markdown.Markdown(
                extensions=[
                           'markdown.extensions.extra',
                           'markdown.extensions.codehilite',
                           ]
                )
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Independentarticle,self).save(*args,**kwargs)


    def __str__(self):
        return self.title



    #定义 get_absolute_url 方法 获取自身的url 
    def get_absolute_url(self):
        # urls.py   中 request 传入的是 id
        # views.py  中 get_object_or_404()函数传入 pk 参数 id
        return reverse('independentarticle:detail',kwargs={'id':self.pk})
        # article --> independentarticle/urls.py app_name=independentarticle
        # detail  --> independentarticle/urls.py name='detail'

    #统计浏览量
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

users/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.


import os
import hashlib



class UserExt(models.Model):
    user = models.OneToOneField(User,verbose_name="用户名")                              #与User 表 建立一对一关系
    realname = models.CharField(max_length=64,verbose_name="真实姓名")                   # 真实姓名
    birthday = models.DateTimeField(blank=True,verbose_name="生日")                      # 生日
    nickname = models.CharField(max_length=64,blank=True,verbose_name="昵称")            # 昵称
    avatar = models.CharField(max_length=256,blank=True,verbose_name="头像")             # 头像
    telephone = models.CharField(max_length=32,blank=True,verbose_name="电话")           # 电话
    score = models.IntegerField(default=0,verbose_name="积分")                           # 积分
    logintime = models.DateTimeField(verbose_name="登陆时间")                            # 登录时间
    validkey = models.CharField(max_length=256,blank=True,verbose_name="验证key")        # key
    status = models.IntegerField(default=0,verbose_name="账号状态")                      # 状态

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'

    @classmethod
    def gen_validkey(cls):
        m = hashlib.md5()
        m.update(os.urandom(32))
        #生成一个随机数，并用MD5加密
        return m.hexdigest()

    def __str__(self):
        return self.realname
   
    def nickname_text(self):
        return self.user.username if self.nickname == '' else self.nickname

users/forms.py
#encoding: utf-8

from django import forms

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate


from .models import UserExt

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput,error_messages={'required':'用户名不能为空'})
    password = forms.CharField(widget=forms.PasswordInput,error_messages={'required':'密码不能为空'})
    password2 = forms.CharField(widget=forms.PasswordInput,required=False)
    email = forms.EmailField(error_messages={'required':'邮箱不能为空','invalid':'邮箱格式不正确'})

    def clean_username(self):
        username = self.cleaned_data.get('username','')
        if len(username) < 6 or len(username) > 16:
            raise forms.ValidationError('用户名必须为6位到16位')
        try:
            User.objects.get(username=username)
            raise forms.ValidationError('用户名已经存在')
        except ObjectDoesNotExist as e:
            pass

        return username

    def clean_password(self):
        password = self.cleaned_data.get('password','')
        if len(password) < 6 or len(password) > 32:
            raise forms.ValidationError('密码必须为6到32位')

        return password

    def clean_email(self):
        password = self.cleaned_data.get('password','')
        password2 = self.cleaned_data.get('password2','')

        if password != password2:
            raise forms.ValidationError('两次密码不一致')

        return password2

    def clean_email(self):
        email = self.cleaned_data.get('email','')
        #username = self.cleaned_data.get('username','')
        try:
            User.objects.get(email=email)
            #User.objects.filter(email=email,username=username)
            #print('user:',user)
            raise forms.ValidationError('邮箱已注册1')
        except ObjectDoesNotExist as e:
            #raise forms.ValidationError('邮箱已注册2')
            pass

        return email


class LoginForm(forms.Form):
    username = forms.CharField(required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.cached_user = None

    def clean(self):
        #cleaned_data = super(LoginForm, self).clean() python 2.7
        cleaned_data = super().clean()
        username = cleaned_data.get('username', '')
        password = cleaned_data.get('password', '')

        if username == '' or password == '':
            raise forms.ValidationError("用户或密码不正确")
        else:
            # user = authenticate(username=username, password=password)
            user = None
            try:
                user = User.objects.get(username=username)
            except ObjectDoesNotExist as e:
                try:
                    user = User.objects.get(email=username)
                except ObjectDoesNotExist as e:
                    pass

            if user and user.check_password(password):
                if user.userext.status == 1:
                    self.cached_user = user
                elif user.userext.status == 0:
                    #发送激活邮件
                    raise form.ValidationError("用户未激活，请查收邮件重新激活")
                    pass
            else:
                raise forms.ValidationError("用户或密码不正确")

        return cleaned_data



class ResetPasswordForm(forms.Form):
    username = forms.CharField(required=False)
    email = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.cached_user = None

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username', '')
        email = cleaned_data.get('email', '')

        if username == '' or email == '':
            raise forms.ValidationError("用户名或邮箱错误")

        try:
            user = User.objects.get(username=username, email=email)
            if user.userext.status != 1:
                raise forms.ValidationError("用户不可用, 请联系管理员")

            self.cached_user = user
        except ObjectDoesNotExist as e:
            raise forms.ValidationError("用户名或邮箱错误")

        return cleaned_data




class ResetPasswordConfirmForm(forms.Form):
    username = forms.CharField(widget=forms.HiddenInput, required=False)
    validkey = forms.CharField(widget=forms.HiddenInput, required=False)
    password = forms.CharField(widget=forms.PasswordInput, error_messages={'required' : '密码不能为空'})
    password2 = forms.CharField(widget=forms.PasswordInput, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.cached_user = None

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username', '')
        validkey = cleaned_data.get('validkey', '')

        if username == '' or validkey == '':
            raise forms.ValidationError("用户名或验证码错误")

        try:
            user = User.objects.get(username=username)
            if user.userext.status != 1:
                raise forms.ValidationError("用户不可用, 请联系管理员")

            # if user.userext.validkey !='' or user.userext.validkey != validkey:
            if user.userext.validkey != validkey:
                raise forms.ValidationError("用户名或验证码错误")

            self.cached_user = user
        except ObjectDoesNotExist as e:
            raise forms.ValidationError("用户名或验证码错误")

        return cleaned_data

    def clean_password(self):
        password = self.cleaned_data.get('password', '')
        if len(password) < 6 or len(password) > 32:
            raise forms.ValidationError('密码必须为6位到32位')
        return password

    def clean_password2(self):
        password = self.cleaned_data.get('password', '')
        password2 = self.cleaned_data.get('password2', '')
        if password != password2:
            raise forms.ValidationError('两次密码不一致')

        return password2




class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, error_messages={'required' : '原密码不能为空'})
    password = forms.CharField(widget=forms.PasswordInput, error_messages={'required' : '密码不能为空'})
    password2 = forms.CharField(widget=forms.PasswordInput, required=False)

    def __init__(self, user, *args, **kwargs):
        #super().__init__(*args, **kwargs)
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password', '')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('原密码不正确')
        return old_password


    def clean_password(self):
        password = self.cleaned_data.get('password', '')
        if len(password) < 6 or len(password) > 32:
            raise forms.ValidationError('密码必须为6位到32位')
        return password

    def clean_password2(self):
        password = self.cleaned_data.get('password', '')
        password2 = self.cleaned_data.get('password2', '')
        if password != password2:
            raise forms.ValidationError('两次密码不一致')

        return password2



class UserExtBaseForm(forms.ModelForm):
    sex = forms.ChoiceField(widget=forms.RadioSelect, choices=[(1, '男'), (0, '女')])
    
    class Meta:
        model = UserExt
        fields = ['realname', 'nickname', 'birthday', 'telephone', 'sex']
        labels = {
            'realname' : '真实名称',
            'nickname' : '昵称',
            'birthday' : '出生日期',
            'telephone' : '电话号码',
            'sex' : '性别',
        }
        widgets = {
        }
        error_messages = {
            'realname' : {
                'required' : '真实名称不能为空'
            }
        }
        help_texts = {
            'realname' : '您的真实名称'
        }

    def clean_realname(self):
        realname = self.cleaned_data.get('realname', '')
        if len(realname) > 10:
            raise forms.ValidationError('真实名称不能大于10个字符串')

        return realname




class UserExtAvatarForm(forms.ModelForm):
    avatar = forms.ImageField(label='头像', error_messages={'invalid_image' : '请输入正确头像'})
    class Meta:
        model = UserExt
        fields = ['avatar']

independentarticle/views.py
from django.shortcuts import render,get_object_or_404
from independentarticle.models import Independentarticle
import markdown
# Create your views here.

from django.http import HttpResponse
import pygments
from comments.forms import CommentForm

from django.views.generic import DetailView



def detail(request,id):
    #pk primary_key 主键
    article= get_object_or_404(Independentarticle,pk=id)

    #阅读量+1
    article.increase_views()

    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'markdown.extensions.toc',
                                               ]
                                    )
    form = CommentForm()
    comment_list = article.comment_set.all()

    context={
             'article':article,
             'form':form,
             'comment_list':comment_list
            }
    return render(request,'independentarticle/independentarticle.html',context=context)

#temp
#文章 基于类
class IndependentarticleDetailView(DetailView):
    model= Independentarticle
    template_name = 'independentarticle/independentarticle.html'
    context_object_name = 'article'

    def get(self,request,*args,**kwargs):
        response= super(IndependentarticleDetailView,self).get(request,*args,**kwargs)
        self.object.increase_view()
        return response

    def get_object(self,queryset=None):
        article = super(IndependentarticleDetailView,self).get_object(queryset=None)
        article.body = markdown.markdown(
                                        article.body,
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',
                                                   ]
                                        )       
        return article

    def get_context_data(self,**kwargs):
        context = super(IndependentarticleDetailView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
                      'form':form,
                      'comment_list':comment_list
                      })
        return context

independentarticle/templates/independentarticle/independentarticle.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block title %}文章详情{% endblock %}

{% block path %}
                <a href="/">首页 >></a> 
                {{article.category.name}} >>
                <a href="/independentarticle/{{article.pk}}">{{article.title}}</a>
{% endblock %}


{% block content %}
<div class="container">
    <div class="col-11 columns" id="mainbody" role="main">
        <div class="post-single type-post">
            <h1 class="article-h1">{{article.title}}</h1>
            <div class="details-up">
  	    <span class="author">作者: <a href="/">{{article.author}}</a></span>
  
            <span class="category">分类: <a href="/">{{article.category.name}}</a></span>
  
            <span class="date">时间: {{article.create_time}}</span>
            <span class="comments-top" itemprop="interactionCount">评论：<a itemprop="discussionUrl" href="/">{{ article.comment_set.count }}条评论</a></span>
            <span class="comments-top" itemprop="interactionCount">浏览：<a itemprop="discussionUrl" href="/">{{ article.views }}人看过</a></span>
  
            <span class="date">标签:
            {% for tag in article.tags.all %}
            <a href="/">{{tag.name}}</a>
            {% endfor %}
            </span>

            </div>
            
            <div class="entry">
            <!--文章正文-->
            {{article.body | safe}}
            </div>




            <div itemprop="keywords" class="tags-meta">
                标签:
                     {% for tag in article.tags.all %}
                     <a href="{% url 'article:tagurl' tag.pk %}">{{tag.name}}</a>
                     {% endfor %}

            </div>
            <br>

{% endblock %}


{% block comment %}


<div id="comments" class="comments">
    <h3>已有{{ article.comment_set.count }}条评论</h3>
    <ol class="comment-list">
        {% for comment in comment_list %}
        <li class="comment-body">
            <div class="clearfix">
               <div class="comment-author">
                   <img src="{% static 'comments/picture/comment_name.png' %}">
               </div>
               <div class="comment-meta">
                    <div class="fn">
                       <a href="">{{ comment.name }}</a>
                    </div>
                    <p>{{ comment.text }}</p>
                    <span class="comment-time">时间:{{ comment.create_time }}</span>
               </div>
            </div>
        </li>
        {% empty %}
        暂无评论
        {% endfor %}

    </ol>
</div>


<div id="reply">
</div>

<div id="comment-place">
    <div id="comment-post" class="respond none-resize">
        <div id="respond">
            <h3 id="response">添加新评论</h3>
            <form method="post" id="comment-form" role="form" action="{% url 'comments:independentarticle_comment' article.pk %}">
                {% csrf_token %}
                <p>
                    <label for="{{ form.name.id_for_label }}" class="required">称呼</label>
                    <!-- <input type="text" name="nickname" value="" placeholder="昵称" maxlength="64" required id="id_nickname" /> -->
                    {{ form.name }}
                    {{ form.name.errors }}
                </p>
                <p>
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    <!-- <input type="text" name="email" value="" placeholder="邮箱（可留空）" maxlength="254" id="id_email" /> -->
                    {{ form.email }}
                    {{ form.email.errors }}
                </p>
                <p>
                    <label for="{{ form.url.id_for_label }}">网站</label>
                    <!-- <input type="text" name="url" value="" placeholder="链接（可留空）" maxlength="200" id="id_url" /> -->
                    {{ form.url }}
                    {{ form.url.errors }}
                </p>
                <p>
                    <label for="{{ form.text.id_for_label }}" class="required">内容</label>
                    <!-- <textarea name="content" cols="40" rows="6" required id="id_content"></textarea> -->
                    {{ form.text }}
                    {{ form.text.errors}}
                </p>
                <!--                
                <p>
                    <label style="float:left;">验证码</label>
                    <div class="row" style="margin-top: 8px">
                    <div class="col-xs-4"><input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text" placeholder="验证码" /> <input id="id_captcha_0" name="captcha_0" type="hi
dden" value="bf1a523df57b7cccdbcb030128087c17914b2270" />
                    </div>
                    <div class="col-xs-4">
                        <img src="picture/e79da8a0db0947aebdcca042b1f8b118.gif" alt="captcha" class="captcha" height="25" />
                    </div>  
                    </div> 
                </p>
                -->
                <p>
                    <button type="submit" class="submit">提交评论</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}